//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Dias.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_SURVEY_NAME                  105
#define IDS_MARKER_KERNEL_NONE          105
#define IDS_MARKER_KERNEL_ROUND         106
#define IDS_MARKER_KERNEL_X             107
#define ID_INDICATOR_TOOL               108
#define IDS_MARKER_KERNEL_PLUS          108
#define ID_INDICATOR_SAVE               109
#define IDS_MARKER_KERNEL_ASTERIX       109
#define ID_INDICATOR_PRINT              110
#define IDS_MARKER_KERNEL_SYMBOL        110
#define ID_INDICATOR_PROGRAM            111
#define ID_INDICATOR_IMG                112
#define ID_INDICATOR_SRV                113
#define ID_INDICATOR_REP                114
#define ID_INDICATOR_SIZEICO            115
#define ID_INDICATOR_SIZE               116
#define ID_INDICATOR_CMICO              117
#define ID_INDICATOR_CM                 118
#define ID_INDICATOR_BPP                119
#define ID_INDICATOR_TIME               120
#define ID_INDICATOR_GEOMSCALE          123
#define ID_INDICATOR_DENSSCALE          124
#define ID_INDICATOR_GEOMSCALEICO       125
#define ID_INDICATOR_DENSSCALEICO       126
#define IDR_MAINFRAME                   128
#define IDR_DISTYPE                     129
#define ID_INDICATOR_PROGRAMICO         132
#define ID_INDICATOR_PRINTICO           133
#define ID_INDICATOR_IMGICO             134
#define ID_INDICATOR_CNLICO             135
#define ID_INDICATOR_CNL                136
#define ID_INDICATOR_PTCICO             137
#define ID_INDICATOR_PTC                138
#define ID_INDICATOR_MRK                139
#define IDR_POPUP_DOC_EMPTY             140
#define ID_INDICATOR_MRKICO             140
#define IDR_POPUP_DOC_ITEM              141
#define ID_PATCH_NAME                   142
#define ID_IMAGE_NAME                   143
#define IDB_IL_DOCTYPES                 153
#define IDR_POPUP_DOC_ADDIMG            154
#define IDR_POPUP_DOC_ADDDB             155
#define IDR_POPUP_DOC_ADDRPT            156
#define IDR_POPUP_DOC_ZOOM              163
#define IDC_POINTER                     164
#define IDC_IOBJCREATE                  166
#define IDC_MRKCREATE                   167
#define IDCX_ZOOMIN_AREASEL             168
#define IDC_CURSOR2                     169
#define IDC_CURSOR3                     170
#define IDC_CURSOR4                     171
#define IDCX_IOBJPTR_MOVE               175
#define IDC_MRKPTR                      176
#define IDC_TEXTCNG                     177
#define IDC_CURSOR11                    178
#define IDC_TEXTCREATE                  179
#define IDB_TBX_STD_H                   180
#define IDB_TBX_STD_N                   181
#define IDB_TBX_STD_D                   182
#define IDB_TBP_IMAGE_H                 190
#define IDI_WS_MARKER_CENTER            191
#define IDI_WS_MARKER_ZOOM              192
#define IDR_POPUP_MARKER_STYLE          195
#define IDR_POPUP_MARKER_KRNLSTYLE      200
#define IDR_POPUP_MARKER_SHPSTYLE       201
#define IDB_IL_COLORMODELS              203
#define IDI_PIC_SIZE                    208
#define IDI_PIC_OFFX                    211
#define IDI_PIC_OFFY                    212
#define IDI_PIC_FILL                    213
#define IDI_PIC_SIZEX                   214
#define IDI_PIC_SIZEY                   215
#define IDI_PIC_ROTATE                  216
#define IDI_PIC_LOCKED                  217
#define IDI_PIC_UNLOCKED                218
#define IDI_MRK_CENTER                  219
#define IDI_PIC_RIGTHARROW              221
#define IDI_PIC_RIGHT                   221
#define IDD_PREF_DENSSCALE              223
#define IDB_DENSSCALES                  224
#define IDD_PREF_GEOMSCALE              224
#define IDB_DENSTYPES                   225
#define IDI_INDICATOR_GEOMSCALE         226
#define IDI_INDICATOR_DENSSCALE         227
#define IDB_GEOMSCALES                  227
#define IDC_HAND                        231
#define IDI_PIC_UP                      231
#define IDI_PIC_DOWN                    232
#define IDI_PIC_REMOVE                  233
#define IDI_PIC_HAND                    237
#define IDI_PIC_ZOOM                    238
#define IDI_PIC_ZOOM1                   239
#define IDB_IL_OBJECTS                  239
#define IDI_PIC_ZOOMFIT                 240
#define IDB_IL_FIELDTYPES               240
#define IDI_PIC_TOGGLE                  241
#define IDI_INDICATOR_IMGICO            243
#define IDI_INDICATOR_CNLICO            244
#define IDI_INDICATOR_PTCICO            245
#define IDI_INDICATOR_MRKICO            246
#define IDI_INDICATOR_PRG_STOP          247
#define IDI_INDICATOR_PRG_PAUSE         248
#define IDI_INDICATOR_PRG_START         249
#define IDI_INDICATOR_SAVE              250
#define IDI_INDICATOR_OPEN              251
#define IDI_INDICATOR_IMPORT            252
#define IDI_INDICATOR_EXPORT            253
#define IDD_TITLES                      256
#define IDI_ICON_IMAGES                 257
#define IDI_ICON_SURVEY                 258
#define IDI_POINTER                     259
#define IDR_TOOLBOX_IMAGES              261
#define IDB_TOOLBOX_IMAGES              265
#define IDD_PANE_MARKERS                268
#define IDB_IL_MARKERKERNELS            269
#define IDD_PANE_ACQUIRE                269
#define IDI_PIC_TRANSPARENT             270
#define IDI_PIC_FORMFACTOR              271
#define IDR_SETTINGS                    274
#define IDB_BITMAP1                     277
#define IDB_LOGO                        277
#define IDR_MENU1                       278
#define IDR_POPUP_TOOLPANE              278
#define IDR_POPUP_IMG                   279
#define IDC_DN_DIMX                     1003
#define IDC_DN_DIMY                     1004
#define IDC_DAI_COUNT                   1005
#define IDC_DN_BPP                      1005
#define IDC_DN_MODEL                    1007
#define IDC_DN_COUNT                    1008
#define IDC_COUNT_PROMPT                1012
#define IDC_COUNT_COUNT                 1013
#define IDC_COUNT_SPIN                  1014
#define IDC_PRM_KRNL_SIZE               1022
#define IDC_EDIT1                       1023
#define IDC_DN_DESCRIPTION              1023
#define IDC_DS_NAME                     1023
#define IDC_DS_DESCR                    1024
#define IDC_EDIT2                       1024
#define IDC_PTM_KRNL_TRANSP             1024
#define IDC_DS_A                        1025
#define IDC_EDIT3                       1025
#define IDC_PTM_SHP_TRANSP              1025
#define IDC_DS_B                        1026
#define IDC_PTM_SHP_FORM                1026
#define IDC_DS_UNITS                    1027
#define IDC_DN_BACKGROUND               1032
#define IDC_DN_DEPTH                    1033
#define IDC_DN_NAME                     1034
#define IDC_DN_BG_WHITE                 1036
#define IDC_DN_BG_BLACK                 1037
#define IDC_DN_BG_CUSTOM                1038
#define IDC_DN_CREATE_MANUAL            1039
#define IDC_DN_CREATE_ARCUIRE           1040
#define IDC_DN_SOURCE                   1041
#define IDC_DN_MODELS                   1048
#define IDC_DAI_SIZE_DOC                1049
#define IDC_DAI_SIZE_IMG                1050
#define IDC_DAI_MODEL_DOC               1051
#define IDC_DAI_MODEL_IMG               1052
#define IDC_DAI_DEPTH_DOC               1053
#define IDC_DAI_DEPTH_IMG               1054
#define IDC_BUTTON1                     1077
#define IDC_DS_REMOVE                   1078
#define IDC_BUTTON2                     1078
#define IDC_PTM_ADD                     1079
#define IDC_PTM_DOWN                    1080
#define IDC_PTM_UP                      1081
#define IDC_PTM_OPT                     1082
#define IDC_PTM_KRNL_COLOR              1083
#define IDC_PTM_SHP_COLOR               1084
#define IDC_BUTTON3                     1084
#define IDC_BUTTON4                     1085
#define IDC_PTM_OUT_COLOR               1086
#define IDC_CAPTURE_WND                 1093
#define IDC_CAPTURE_TOGGLE              1094
#define IDC_CAPTURE_CAPTURE             1095
#define IDC_CAPTURE_OPTIONS             1096
#define IDC_DS_LIST                     1100
#define IDC_DS_TYPES                    1101
#define IDC_DS_SELECT                   1103
#define IDC_DS_ADD                      1104
#define IDC_GS_LIST                     1105
#define IDC_GS_ADD                      1106
#define IDC_GS_REMOVE                   1107
#define IDC_GS_SELECT                   1108
#define IDC_GS_NAME                     1109
#define IDC_GS_DESCR                    1110
#define IDC_GS_A                        1111
#define IDC_GS_B                        1112
#define IDC_GS_UNITS                    1113
#define IDC_CD_LIST                     1114
#define IDC_CD_BUTTON                   1115
#define IDC_CD_GRIPPER                  1116
#define IDC_DAS_TREE                    1117
#define IDC_DAS_INFO                    1118
#define IDC_DAS_LIST                    1120
#define IDC_RADIO1                      1122
#define IDC_RADIO2                      1123
#define IDC_RADIO3                      1124
#define IDC_CAPTURE_POSAFTER            1125
#define IDC_COMBO1                      1126
#define IDC_CAPTURE_POSBEFORE           1126
#define IDC_CHECK2                      1127
#define IDC_3IFN_3TYPE                  1127
#define IDC_CHECK3                      1128
#define IDC_3IFN_1TYPE                  1128
#define IDC_CHECK4                      1129
#define IDC_CHECK5                      1130
#define IDC_CHECK6                      1131
#define IDC_COMBO2                      1132
#define IDC_COMBO3                      1133
#define IDC_CAPTURE_SAVE                1133
#define IDC_COMBO4                      1134
#define IDC_CAPTURE_IMPORT              1134
#define IDC_COMBO5                      1135
#define IDC_CAPTURE_DELETE              1135
#define IDC_COMBO6                      1136
#define IDC_CHECK1                      1137
#define IDC_EDIT4                       1138
#define IDC_CHECK10                     1138
#define IDC_RADIO4                      1139
#define IDC_CHECK11                     1139
#define IDC_RADIO5                      1140
#define IDC_CHECK12                     1140
#define IDC_CHECK7                      1141
#define IDC_CHECK13                     1141
#define IDC_CHECK8                      1142
#define IDC_CHECK9                      1143
#define IDC_EDIT5                       1144
#define IDC_3IFN_RESET                  1146
#define IDC_DAS_UP                      1147
#define IDC_3IFN_APPLY                  1147
#define IDC_DAS_DOWN                    1148
#define IDC_DAS_REMOVE                  1149
#define IDC_3IFN_2TYPE                  1152
#define IDC_3IFN_1SRC                   1153
#define IDC_3IFN_2SRC                   1154
#define IDC_3IFN_PREVIEW                1155
#define IDC_3IFN_3SRC                   1156
#define IDC_CAPTURE_IMGNAME             1157
#define IDC_CAPTURE_POSTOP              1158
#define IDC_CAPTURE_POSEND              1159
#define IDC_CAPTURE_AUTONAME            1160
#define IDC_3IFN_AUTO                   1161
#define IDC_CAPTURE_NO                  1161
#define IDC_3IFN_HAND                   1162
#define IDC_DAS_OBJECT                  1162
#define IDC_CAPTURE_STEP                1162
#define IDC_3IFN_ZOOM                   1163
#define IDC_DAS_LOAD                    1163
#define IDC_CAPTURE_SEQNO               1163
#define IDC_3IFN_ZOOM1                  1164
#define IDC_DAS_SAVE                    1164
#define IDC_CAPTURE_SEQ                 1164
#define IDC_3IFN_ZOOMFIT                1165
#define IDC_DAS_DESCRIPT                1165
#define IDC_CAPTURE_SEQNAME             1165
#define IDC_3IFN_TOGGLE                 1166
#define IDC_CAPTURE_AUTO                1166
#define IDC_CAPTURE_SEC                 1167
#define IDC_CAPTURE_INTEGR              1168
#define IDC_CAPTURE_INTERGNO            1169
#define IDC_TITLES_TITLE                1175
#define IDC_TITLES_DESCR                1176
#define IDC_CD_NEW                      1177
#define IDC_CAPTURE_PRESENTS            1177
#define IDC_CD_TOP                      1178
#define IDC_DAI_SELECT                  1178
#define IDC_CD_UP                       1179
#define IDC_DAI_SELECTADD               1179
#define IDC_CD_DELETE                   1180
#define IDC_DAI_NAME                    1180
#define IDC_CD_DOWN                     1181
#define IDC_DAI_DESCR                   1181
#define IDC_CD_BOTTOM                   1182
#define IDC_CD_MENU                     1183
#define IDC_DAI_TEMPL2                  1183
#define IDC_DAI_TEMPL3                  1184
#define IDC_DAI_POSTOP                  1185
#define IDC_DAI_POSEND                  1186
#define IDC_DAI_POSBEFOREACT            1187
#define IDC_DAI_POSAFTERACT             1188
#define IDC_DAI_POSBEFORESEL            1189
#define IDC_DAS_NAME                    1189
#define IDC_DAI_POSAFTERSEL             1190
#define IDC_DAS_DESCR                   1190
#define IDC_DAI_POSEVERY                1191
#define IDC_DAS_IMPORT                  1191
#define IDC_DAS_DELETE                  1192
#define IDC_DAS_PRESENTS                1193
#define IDC_DN_PRESENTS                 1194
#define IDC_DN_SAVE                     1195
#define IDC_DN_IMPORT                   1196
#define IDC_DN_DELETE                   1197
#define IDC_DN_DEVICES                  1198
#define IDC_PTM_LIST                    1200
#define IDC_PTM_KERNEL                  1201
#define IDC_PTM_SHAPE                   1202
#define IDC_PTM_KERNEL2                 1202
#define IDC_PTM_OUT_STYLE               1203
#define IDC_PTM_DELETE                  1204
#define IDC_PTM_OUT_WIDTH               1208
#define IDC_PTM_EDT_KSZ                 1214
#define IDC_PTM_EDT_KTP                 1215
#define IDC_PTM_EDT_STP                 1218
#define IDC_PTM_EDT_SFRM                1219
#define IDC_PTM_LCK_KSZ                 1220
#define IDC_PTM_LCK_SSZ                 1221
#define IDC_PTM_LCK_SROT                1222
#define IDC_PTM_STATIC_KRNL             1223
#define IDC_PTM_STATIC_KRNL_LINE        1224
#define IDC_PTM_STATIC_SHP              1225
#define IDC_PTM_STATIC_SHP_LINE         1226
#define IDC_PTM_STATIC_SIZE             1227
#define IDC_PTM_STATIC_SIZE_LINE        1228
#define IDC_PTM_EDT_KOFFX               1229
#define IDC_PTM_STATIC_SHP2             1229
#define IDC_PTM_EDT_KOFFY               1230
#define IDC_PTM_STATIC_SHP3             1230
#define IDC_PTM_EDT_SSZX                1231
#define IDC_PTM_EDT_SSZY                1232
#define IDC_PTM_EDT_SSZX2               1232
#define IDC_PTM_EDT_SROT                1233
#define IDC_PTM_EDT_SSZX3               1233
#define IDC_PTM_EDT_SSZX4               1234
#define IDC_PTM_EDT_SSZX5               1235
#define IDC_PTM_STATIC_KRNL_LINE2       1236
#define IDC_PTM_STATIC_KRNL2            1237
#define ID_TOOLS_GEOMSCALE_1            24000
#define ID_TOOLS_GEOMSCALE_999          24999
#define ID_TOOLS_DENSSCALE_1            25000
#define ID_TOOLS_DENSSCALE_999          25999
#define IDC_ZOOMIN                      30978
#define IDC_ZOOMOUT                     30988
#define IDCX_ZOOMOUT_AREASEL            30989
#define IDC_MRKPTR_MOVE                 30990
#define IDC_MRKPTR_SIZEX                30991
#define IDC_MRKPTR_SIZEY                30992
#define IDC_MRKPTR_SIZEXY               30993
#define IDC_MRKPTR_ROT                  30995
#define IDC_MRKSEL                      30996
#define IDC_MRKPTR_SIZEYROT             30998
#define IDC_MRKPTR_SIZEXYROT            30999
#define IDC_MRKPTR_SIZEXROT             31000
#define IDC_HANDSHAKE                   31001
#define IDC_IOBJCREATE_INCL             31002
#define IDC_IOBJCREATE_XOR              31003
#define IDC_IOBJCREATE_EXCL1            31004
#define IDC_IOBJCREATE_EXCL             31004
#define ID_EDIT_ADD                     32771
#define ID_EDIT_REMOVE                  32782
#define ID_EDIT_UP                      32783
#define ID_EDIT_DOWN                    32784
#define ID_EDIT_PREV                    32785
#define ID_EDIT_NEXT                    32786
#define ID_EDIT_PROP                    32787
#define ID_EDIT_STYLE_BIG               32789
#define ID_EDIT_STYLE_SMALL             32790
#define ID_DOC_ADD_IMAGE                32791
#define ID_DOC_ADD_SEQUENCE             32792
#define ID_DOC_ADD_ACQUIRE              32793
#define ID_DOC_ADD                      32794
#define ID_DOC_REMOVE                   32795
#define ID_TOOLBOX_PTR                  32801
#define ID_TOOLBOX_HAND                 32810
#define ID_DOC_ADD_IMPORTIMG            32817
#define ID_DOC_ADD_IMPORTSEQ            32818
#define ID_DOC_ADD_REPORT               32819
#define ID_DOC_ADD_DB                   32820
#define ID_DOC_ADD_DBMEASURE            32821
#define ID_DOC_ADD_IMPORTDB             32822
#define ID_VIEW_TOOLBAR_STD             32823
#define ID_VIEW_TOOLBOX                 32824
#define ID_VIEW_IMAGES                  32825
#define ID_VIEW_DATA                    32826
#define ID_VIEW_REPORTS                 32827
#define ID_VIEW_CLIENT                  32828
#define ID_VIEW_ZOOM                    32830
#define ID_TOOLBOX_ZOOM                 32830
#define ID_VIEW_ZOOM_FIT                32832
#define ID_VIEW_ZOOM_1TO1               32833
#define ID_VIEW_ZOOM_25                 32834
#define ID_VIEW_ZOOM_33                 32835
#define ID_VIEW_ZOOM_50                 32836
#define ID_VIEW_ZOOM_66                 32837
#define ID_VIEW_ZOOM_75                 32838
#define ID_VIEW_ZOOM_125                32839
#define ID_VIEW_ZOOM_150                32840
#define ID_VIEW_ZOOM_200                32841
#define ID_VIEW_ZOOM_300                32842
#define ID_VIEW_ZOOM_400                32843
#define ID_VIEW_ZOOM_500                32844
#define ID_VIEW_ZOOM_750                32845
#define ID_VIEW_ZOOM_250                32846
#define ID_VIEW_ZOOM_1000               32847
#define ID_VIEW_ZOOM_OTHER              32848
#define ID_MARKER_INTCOL                32856
#define ID_MARKER_SELSTYLE              32860
#define ID_MARKER_COPYSTYLE             32872
#define ID_MARKER_HELP                  32873
#define ID_MARKER_KERNEL_ROUND          32874
#define ID_MARKER_KERNEL_PLUS           32876
#define ID_MARKER_KERNEL_NONE           32877
#define ID_MARKER_STYLE_ADD             32879
#define ID_MARKER_KERNEL_X              32881
#define ID_EDIT_RENAME                  32895
#define ID_EDIT_SELECT                  32896
#define ID_FILE_SAVEWEB                 32899
#define ID_FILE_INFO                    32900
#define ID_FILE_JUMP_LIGA               32901
#define ID_FILE_JUMP_STANUM             32902
#define ID_FILE_JUMP_SPIDER             32903
#define ID_EDIT_DUPLICATE               32910
#define ID_EDIT_PREFERENCES             32913
#define ID_EDIT_BIG                     32942
#define ID_EDIT_SMALL                   32943
#define ID_VIEW_TOOLBAR_EDIT            32944
#define ID_FILE_SAVEAS                  32945
#define ID_FILE_IMPORT                  32949
#define ID_FILE_EXPORT                  32950
#define ID_WINDOW_CLOSE                 32971
#define ID_EDIT_CUSTOMIZE               32974
#define ID_VIEW_FULLSCREEN              32977
#define ID_VIEW_HIDE                    32978
#define ID_VIEW_SHOWALL                 32979
#define ID_VIEW_PROPBAR                 32980
#define ID_HELP_PLUGIN_LIST             32983
#define ID_HELP_FEEDBACK                32984
#define ID_HELP_HELPER                  32985
#define ID_FILE_MAIL                    32988
#define ID_EDIT_DELETE                  32989
#define ID_IMAGE_PLUGINS                32990
#define ID_SURVEY_MEASURE               32999
#define ID_EDIT_GEOMSCALES              33000
#define ID_EDIT_DENSSCALES              33001
#define ID_VIEW_SCALE                   33002
#define ID_VIEW_IMAGE                   33003
#define ID_VIEW_PATCHES                 33004
#define ID_VIEW_MARKS                   33005
#define ID_VIEW_TEXTS                   33006
#define ID_VIEW_METRICS                 33007
#define ID_VIEW_HEADERS                 33008
#define ID_TOOLS_PREFERENCES            33009
#define ID_TOOLS_IMPORTPREFS            33010
#define ID_TOOLS_EXPORTPREFS            33011
#define ID_TOOLS_MACRO                  33012
#define ID_SURVEY_IMPORT                33016
#define ID_SURVEY_EXPORT                33017
#define ID_TOOLS_PLUGINS_1              33022
#define ID_SURVEY_ADD                   33032
#define ID_SURVEY_FIELDS                33034
#define ID_TOOLS_PLUGINS_2              33035
#define ID_TOOLS_PLUGINS_3              33084
#define ID_MARKER_SHAPE_NONE            33086
#define ID_MARKER_SHAPE_ELLIPSE         33087
#define ID_MARKER_SHAPE_TRI             33088
#define ID_MARKER_SHAPE_RECT            33089
#define ID_MARKER_STYLE_IMPORT          33090
#define ID_MARKER_STYLE_EXPORT          33091
#define ID_MARKER_STYLE_DELETE          33092
#define ID_MARKER_STYLE_RENAME          33094
#define ID_MARKER_STYLE_DUPLICATE       33095
#define ID_MARKER_AUTOIMPORT            33096
#define ID_IMAGE_POINTER                33097
#define ID_IMAGE_HAND                   33098
#define ID_IMAGE_SELECT                 33099
#define ID_IMAGE_ZOOM                   33100
#define ID_IMAGE_ACQUIRE                33101
#define ID_IMAGE_MEASURE                33102
#define ID_IMAGE_MARKER                 33103
#define ID_IMAGE_PATCH                  33104
#define ID_IMAGE_LABEL                  33105
#define ID_IMAGE_PICKER                 33106
#define ID_IMAGE_PEN                    33107
#define ID_IMAGE_SHAPE                  33108
#define ID_IMAGE_TEXT                   33109
#define ID_IMAGE_FILL                   33110
#define ID_IMAGE_ERASER                 33111
#define ID_FILE_NEW_STORAGE             33113
#define ID_FILE_NEW_PROCESSOR           33116
#define ID_FILE_SAVEALL                 33117
#define ID_FILE_PREVIEW                 33118
#define ID_FILE_PAGESETUP               33119
#define ID_FILE_PRINTSETUP              33120
#define ID_FILE_UPLOAD                  33121
#define ID_FILE_DOWNLOAD                33122
#define ID_FILE_SAVEWORKSPACE           33123
#define ID_Menu                         33124
#define ID_FILE_RECENTFILES             33125
#define ID_EDIT_GOTO                    33126
#define ID_EDIT_REPEATLAST              33127
#define ID_EDIT_PASTESPECIAL            33129
#define ID_VIEW_THUMBINALS              33131
#define ID_VIEW_CONTROLPANELS           33132
#define ID_EDIT_REMOVESELECTION         33133
#define ID_CONTROLPANELS_DOCUMENTINFO   33134
#define ID_CONTROLPANELS_COMPONENTS     33135
#define ID_CONTROLPANELS_SETTINGS       33136
#define ID_CONTROLPANELS_FINDREPLACE    33137
#define ID_CONTROLPANELS_GRIDGUIDELINES 33138
#define ID_CONTROLPANELS_FILTERS        33139
#define ID_CONTROLPANELS_HISTORY        33140
#define ID_CONTROLPANELS_TOOLSETTINGS   33141
#define ID_CONTROLPANELS_CREATENEW      33142
#define ID_CONTROLPANELS_PROCESSOR      33143
#define ID_VIEW_SCALE33144              33144
#define ID_VIEW_FILTERS                 33145
#define ID_FILE_ACQUIRE                 33146
#define ID_TOOLBARS_MACROS              33147
#define ID_TOOLBARS_AIMSUITE            33148
#define ID_TOOLBARS_WINDOW              33149
#define ID_STORAGE_RESAMPLE             33153
#define ID_STORAGE_CROP                 33154
#define ID_STORAGE_PROCESS              33155
#define ID_STORAGE_MEASURE              33156
#define ID_STORAGE_REPORT               33157
#define ID_STORAGE_MODEL_BW             33158
#define ID_STORAGE_MODEL_GREYSCALE      33159
#define ID_STORAGE_MODEL_RGB            33160
#define ID_STORAGE_MODEL_CMY            33161
#define ID_STORAGE_MODEL_CMYK           33162
#define ID_STORAGE_MODEL_LAB            33163
#define ID_STORAGE_MODEL_MULTY          33164
#define ID_STORAGE_BPP1                 33165
#define ID_STORAGE_BPP4                 33166
#define ID_STORAGE_BPP8                 33167
#define ID_STORAGE_BPP16                33168
#define ID_STORAGE_BPP32                33169
#define ID_STORAGE_BPPOTHER             33170
#define ID_STORAGE_ROTATE180            33171
#define ID_STORAGE_ROTATE90CW           33172
#define ID_STORAGE_ROTATE90CCW          33173
#define ID_STORAGE_ROTATEARBITRARY      33174
#define ID_STORAGE_ROTATEVERT           33175
#define ID_STORAGE_ROTATEHORZ           33176
#define ID_TOOLS_CUSTOMIZE              33179
#define ID_WINDOW_CLOSEALL              33181
#define ID_WINDOW_MINIMIZEALL           33182
#define ID_WINDOW_MAXIMIZEALL           33183
#define ID_TOOLS_COMPONENTS             33185
#define ID_STORAGE_GEOMSCALES           33186
#define ID_STORAGE_DENSSCALES           33187
#define ID_TASKPANES_GEOMETRICSCALES    33188
#define ID_TASKPANES_DENSITOMETRICSCALES 33189
#define ID_TOOLS_MACROS_RECORD          33194
#define ID_TOOLS_MACROS_PAUSE           33195
#define ID_TOOLS_MACROS_STOP            33196
#define ID_TOOLS_MACROS_PLAY            33197
#define ID_TRANSPARENT_0                33198
#define ID_VIEW_TASKPANE                33207
#define ID_POINTER_ALPHABLENDIMAGE      33208
#define ID_VIEW_OBJECTS                 33212
#define ID_VIEW_LAYERS                  33215
#define ID_VIEW_LAYERS_BACKGROUND       33221
#define ID_VIEW_LAYERS_CELLS            33222
#define ID_VIEW_LAYERS_NUCLEI           33223
#define ID_VIEW_LAYERS_NUCLEOLI         33224
#define ID_VIEW_LAYERS_ETCETERA         33225
#define ID_EDIT_LAYERS_VIEWALL          33228
#define ID_LAYERS_BLENDINACTIVE         33229
#define ID_STORAGE_RESIZE               33230
#define ID_FILE_ACQUIRE_TWAIN           33232
#define ID_FILE_ACQUIRE_WINMAGING       33235
#define ID_VIEW_OBJECTS_BLEND           33237
#define ID_VIEW_OBJECTS_PATCHES         33238
#define ID_VIEW_OBJECTS_MARKS           33239
#define ID_VIEW_FILTERS_ALPHA           33240
#define ID_VIEW_ZOOM_IN                 33242
#define ID_VIEW_ZOOM_OUT                33243
#define ID_Menu33244                    33244
#define ID_TOOLS_BUILD                  33245
#define ID_TOOLS_BUILD_EXTRACTPATCHESBYLAYER 33247
#define ID_TOOLS_BUILD_FINDOUTBGMASK    33250
#define ID_TOOLS_BUILD_REMOVEBACKGROUNDMASK 33252
#define ID_BUILD_WHITENOISECOMPUTATIOS  33253
#define ID_TOOLS_BUILD_MEDIANFILTERING  33255
#define ID_TOOLS_BUILD_REMOVENOISE      33257
#define ID_TOOLS_BUILD_NEWNOISEREMOVEPROC4 33259
#define ID_TOOLS_BUILD_LASTMINIMUMSEGMENTATION 33261
#define ID_IPAS_AVERAGE                 33262
#define ID_IPAS_MINIMUM                 33263
#define ID_IPAS_MAXIMUM                 33264
#define ID_IPAS_MEDIAN                  33265
#define ID_STORAGE_LOOKUPTABLESS        33266
#define ID_STORAGE_HISTOGRAMS           33267
#define ID_TASKPANES_LOOKUPTABLES       33268
#define ID_TASKPANES_HISTOGRAMS         33269
#define ID_TOOLS_BUILD_NEWNOISEREMOVEPROC8 33271
#define IDS_TBX_DOC_ADD_IMAGE           61446
#define IDS_TBX_DOC_REMOVE              61447
#define IDS_TBX_DOC_UP                  61448
#define IDS_TBX_DOC_ADD_ACQUIRE         61449
#define IDS_TBX_DOC_IMAGES              61454
#define IDS_TBX_DOC_DB                  61455
#define IDS_TBX_DOC_REPORTS             61456
#define IDS_TBX_IMG                     61457
#define IDS_IMPORTSEQ_DLGCAPTION        61461
#define IDS_IMPORTSEQ_DEFNAME           61462
#define IDS_IMPORTSEQ_OPENERR           61463
#define IDS_IMPORTSEQ_TYPEERR           61464
#define IDS_IMPORTSEQ_SIZEERR           61465
#define IDS_TBX_DOC_ZOOM                61466
#define IDS_ERR_SYS_MEMRES              61467
#define IDS_ERR_SYS_MEMCOM              61468
#define IDS_ERR_SYS_MEMDECOM            61469
#define IDS_ERR_SYS_MEMREL              61470
#define IDS_MARKER_COPYSTYLE            61471
#define IDS_MARKER_SELSTYLE             61472
#define IDS_TBP_MRKCREATE               61473
#define IDS_CM_BW                       61474
#define IDS_CM_GRAY                     61475
#define IDS_CM_RGB                      61476
#define IDS_CM_CMY                      61477
#define IDS_CM_CMYK                     61478
#define IDS_CM_LAB                      61479
#define IDS_ERR_DOC_VERSION             61480
#define IDS_ERR_DOC                     61481
#define IDS_COLORMODEL                  61482
#define IDS_BPP                         61483
#define IDS_CHANNELS                    61484
#define IDS_CM_MULTY                    61485
#define IDS_TBX_DOC_ADD_DB              61486
#define IDS_TBX_DOC_MEASURE             61487
#define IDS_DLG_CAPTURE_LIVE            61488
#define IDS_DLG_CAPTURE_STOP            61489
#define IDS_REG_ROOT                    61490
#define IDS_MBTITLE_APP                 61491
#define IDS_MBTEXT_REGERR               61492
#define IDS_MBTEXT_FSETERR              61493
#define IDS_MBTEXT_FSETWERR             61494
#define IDS_PREFERENCES                 61495
#define IDS_DENS_COL_NAME               61496
#define IDS_DENS_COL_COEF1              61497
#define IDS_DENS_COL_COEF2              61498
#define IDS_DENS_COL_UNITS              61499
#define IDS_DENS_COL_DESCRIPT           61500
#define IDS_DENS_TYPE_LINEAR            61501
#define IDS_DENS_TYPE_POLY              61502
#define IDS_DENS_TYPE_EXP               61503
#define IDS_DENS_TYPE_LOG               61504
#define IDS_MBTEXT_REGWERR              61505
#define IDS_MRKKRNL_NAME                61506
#define IDS_TBX_DOC_IMPORT              61507
#define IDS_TBX_DOC_EXPORT              61508
#define IDS_IMGPB_SHOW                  61509
#define IDS_IMGPB_HIDE                  61510
#define IDS_MRKSHP_NAME                 61511
#define IDS_METRICS_PX                  61512
#define IDS_METRICS_PIXELS              61513
#define IDS_METRICS_DEGR                61514
#define IDS_METRICS_DEGREES             61515
#define IDS_MRKSTYLE_NAME               61516
#define IDS_MRKSTYLE_DESCR              61517
#define IDS_DLG_DAS_FIELDCAPTION        61518
#define IDS_DLG_DAS_FIELDNAME           61519
#define IDS_EXPORTSEQ_DLGCAPTION        61520
#define IDS_EXPORTSEQ_OPENERR           61521
#define IDS_MBTITLE_WARNING             61522
#define IDS_MBTEXT_ADDSRVDLG            61523
#define IDS_DLG_DAS_UNIT                61524
#define IDS_TBX_DOC_FIELDS              61525
#define IDS_DLG_DAS_APP                 61526
#define IDS_DLG_DAS_DOC                 61527
#define IDS_DLG_DAS_IMG                 61528
#define IDS_DLG_DAS_CHNL                61529
#define IDS_DLG_DAS_PTCH                61530
#define IDS_DLG_DAS_MRK                 61531
#define IDS_DLG_DAS_USR                 61532
#define IDS_STATUS_READY                61533
#define IDS_MBTEXT_DIASKS_NO            61534
#define IDS_MBTITLE_COLLISION           61535
#define IDS_MBTEXT_COLLISION            61536
#define IDS_MBTITLE_DELETE              61537
#define IDS_MBTEXT_DELETE               61538
#define IDS_MBTITLE_ERROR               61539
#define IDS_MBTEXT_BUILTINDELETION      61540

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        280
#define _APS_NEXT_COMMAND_VALUE         33272
#define _APS_NEXT_CONTROL_VALUE         1234
#define _APS_NEXT_SYMED_VALUE           144
#endif
#endif
